#include<iostream>
#include<conio.h>
#include<math.h>
#include<time.h>
#include<stdlib.h>
#include<windows.h>
//For Positioning the cursor on desired location for output.
void gotoxy(short x, short y) {
COORD pos = {x, y};
SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), pos);}
using namespace std;
using namespace std;

int a,b,c,d,e; // numbers entered by the user
char c1, c2, c3, c4, c5; // check values for position  and number
int A, B, C, D , E;  // set generated by PROGRAM for the player to crack
time_t t;
int i;
int main()
{
     system("cls");
     char ch;
     cout << "\t" << "\t" <<"\t"<< "M A S T E R M I N D ... LOADING Please wait.." << "\n" << "\n";
     LOOP: srand(time(&t));
     A = rand()%8 + 1;
     B = rand()%8 + 1;
     C = rand()%8 + 1;
     D = rand()%8 + 1;
     E = rand()%8 + 1;
     
     
     if(A != B && A != C && A != D && A != E)   //So as to destroy the possibilty of repetition of numbers.
     {
          if(B != C && B != D && B != E)
          {
               if(C != D && C != E)
               {
                    if(D != E)
                    {
                         goto START;
                    }
                    else 
                    {
                    goto LOOP;
                    }
               }
               else
               {
                   goto LOOP;
               }
          }
          else 
          {
               goto LOOP;
          }
     }
     else
     goto LOOP;
     
     
     START: system("cls");
            cout << "\t" << "\t"<<"\t" << "WELCOME to M A S T E R M I N D" << "\n" << "\n";
            cout<<"\t"<<"\t"<<"\t"<<"\t";
			for(i=0;i<5;i++)
            {Sleep(1000);
            cout<<"_  ";
			}
			cout << "\n"<<"\n";          
     cout << "TRY TO CRACK THE CODE in 12 turns - enter 5 numbers - all different - from 1 to 8 \n" << "Press space after each\n";
     getch();
     cout << "RULES:\n '*' denotes correct number AND position  while O denotes correct number only \n" << "\n";
     getch();
     cout << "Ready? GO!! \n" ;
     GAME:if(i > 12)
               {
                    cout << "YOU TOOK MORE THAN 12 TURNS-  YOU LOSE!";
                    getch();
                              system("cls"); hg: cout<<"Do You Want To Play Again?(y/n)\n";
ch=getch();
if(ch=='y')
goto LOOP;



}
    AGAIN:      cin >> a >> b >> c >> d >> e;
     
     cout << "\t" << "\t";
     
     if(a != b && a != c && a != d && a != e)   //So as to destroy the possibilty of user entering repetitive numbers.
     {
          if(b != c && b != d && b != e)
          {
               if(c != d && c != e)
               {
                    if(d != e)
                    {    
                         goto FSTART;
                    }
                    else 
                    {cout<<"PLEASE ENTER 'DIFFERENT' NUMBERS!!\n";
                    goto AGAIN;
                    }
               }
               else
               {   cout<<"PLEASE ENTER 'DIFFERENT' NUMBERS!!\n";
                   goto AGAIN;
               }
          }
          else 
          {    cout<<"PLEASE ENTER 'DIFFERENT' NUMBERS!!\n";
               goto AGAIN;
          }
     }
     else
     {
	 cout<<"PLEASE ENTER 'DIFFERENT' NUMBERS!!\n";
     goto AGAIN;
 }
 

 FSTART:
     
     
     if(a == 9 && b == 1 && c == 2 && d == 3 & e == 42)  //cheat code to know the CODE(lol)!
     {
          cout << A <<" "<< B <<" "<< C <<" "<< D <<" "<< E<<" ";
     }        
     
     if(a == 8 && b == 9 && c == 13 && d == 11 && e == 13) //ENDS THE GAME 
     {
          exit(0);
          }
          
     if(a==A)
     {
            c1='*';
            cout << c1;
     }
     
    
     
     
          
  //.....................................................        
     if(b==B)
     {
            c2 = '*';
            cout << c2;
            
            }
     
     
         
     
   //............................................       
          
     if(c==C)
     {
             c3 = '*';
             cout << c3;
             
             }
      

               
   //,..........................................................
     if(d == D)
     {
          c4 = '*';
          cout << c4;
          }
       

     
     
     //................................................
     if(e == E)
     {
          c5 = '*';
          cout << c5;
          }
    
    //_______________________________________ CIRCLE CHECK
     
     if(a == B || a == C || a == D || a == E)
     {
          c1 = 'O';
          cout << c1;
          }
     //,...............................
     if(b == A || b == C || b == D || b == E)
     {
          c2 = 'O';
          cout << c2;
        
        }
     //...............................................
     if(c == B || c == A || c == D || c == E)
     {
          c3 = 'O';
          cout << c3;
          }
     //.......................................................
      if(d == B || d == C || d == A || d == E)
     {
          c4 = 'O';
          cout << c4;
          }
     //............................................
     if(e == B || e == C || e == D || e == A)
     {
          c5 = 'O';
          cout << c5;
          }
     cout << "\n";
     
     if(c1 == '*' && c2 == '*' && c3 == '*' && c4 == '*' && c5 == '*')        // ALL at correct position victory SCENRIO
     {
           cout << "YOU CRACKED THE CODE!! You won in " << i+1 << " tries";
           getch();
           system("cls");
           ag: cout<<"Do You Want To Play Again?(y/n)\n";
       
ch=getch();
if(ch=='y')
goto LOOP;

   }
           
     else                      //LOOP to go back to number entering
     {
          i++;                // counter for number of tries
          goto GAME;
          } 
        

getch();
return 0;
}
